- 👋 Hi, I’m @ahmedtarek333
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
ahmedtarek333/ahmedtarek333 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
apt update

apt upgrade

pkg install python2-dev python2 git -y

git clone https://github.com/CiKu370/OSIF


cd OSIF

ls

pip2 install -r requirements.txt

chmod +x osif.py

python2 osif.py
